[wd-v1-4-vit-tagger]
threshold = 0.35

[wd-v1-4-convnext-tagger]
threshold = 0.35

[wd-v1-4-vit-tagger-v2]
threshold = 0.3537

[wd-v1-4-convnext-tagger-v2]
threshold = 0.3685

[wd-v1-4-convnextv2-tagger-v2]
threshold = 0.371

[wd-v1-4-moat-tagger-v2]
threshold = 0.3771

[wd-v1-4-swinv2-tagger-v2]
threshold = 0.3771

[wd-vit-tagger-v3]
threshold = 0.2614

[wd-convnext-tagger-v3]
threshold = 0.2682

[wd-swinv2-tagger-v3]
threshold = 0.2653

[wd-vit-large-tagger-v3]
threshold = 0.2606

[wd-eva02-large-tagger-v3]
threshold = 0.5296

[BLIPLargeCaptioning]
model_path = "Salesforce/blip-image-captioning-large"

[blip2-opt-2.7b]
model_path = "Salesforce/blip2-opt-2.7b"

[blip2-opt-2.7b-coco]
model_path = "Salesforce/blip2-opt-2.7b-coco"

[blip2-opt-6.7b]
model_path = "Salesforce/blip2-opt-6.7b"

[blip2-opt-6.7b-coco]
model_path = "Salesforce/blip2-opt-6.7b-coco"

[blip2-flan-t5-xl]
model_path = "Salesforce/blip2-flan-t5-xl"

[blip2-flan-t5-xl-coco]
model_path = "Salesforce/blip2-flan-t5-xl-coco"

[blip2-flan-t5-xxl]
model_path = "Salesforce/blip2-flan-t5-xxl"

[GITLargeCaptioning]
model_path = "microsoft/git-large-coco"
